default_platform(:android)

platform :android do
  lane :test do
    gradle_file_path = 'mobile/android/app/build.gradle'
    $project_dir = '**/app'

    if !File.file?(gradle_file_path)
      UI.user_error!("Cannot find the build.gradle file at path: #{gradle_file_path}")
    end

    increment_version_code(
      app_project_dir: $project_dir,
    )

    increment_version_name(
      app_project_dir: $project_dir,
    )

    commit_android_version_bump(
      app_project_dir: $project_dir,
      force: true
    )

    push_to_git_remote
  end
end