name: Android Build

on:
  push:
    branches:
      - main

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print All Secrets
        run: |
          for secret in $(echo ${!secrets[*]}); do
            echo "$secret=${secrets[$secret]}"
          done
