name: Android Build
run-name: ${{github.actor}} is deploying to PlayStore internal track
on:
  issue_comment:
    types: [created, edited, deleted]
  workflow_dispatch:

permissions:
  contents: "write"
  issues: "write"
  pull-requests: write
  id-token: "write"

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'issue_comment' || (github.event.issue.pull_request && startsWith(github.event.comment.body, '/deploy-internal')) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract whitelabel parameter
        run: echo "WHITELABEL=$(echo '${{ github.event.comment.body }}' | sed -n 's|^/deploy-internal-\(.*\)|\1|p')" >> $GITHUB_ENV

      - name: Display whitelabel
        run: echo "running deployment for $WHITELABEL"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: cd mobile && npm install

      - name: Increment version
        run: cd mobile && npm version patch

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Build Android project
        run: cd mobile/android && sudo ./gradlew assembleDebug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            android/app/build/outputs/**/*.apk
            android/app/build/outputs/**/*.aab
