name: Android Build

on:
  push:
    branches:
      - main

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Usar o segredo
        run: echo "MY_SECRET = '${{ secrets.MY_SECRET }}'"

      - name: Usar o segredo
        run: echo MY_SECRET 2 = ${{ secrets.MY_SECRET }}



