name: build-android
run-name: ${{github.actor}} is deploying android app
on:
  issue_comment:
    types: [created, edited, deleted]
  workflow_dispatch:

permissions:
  contents: "write"
  issues: "write"
  pull-requests: "write"
  id-token: "write"

env:
  WHITELABEL: "tupinamba"
  BUMP_TYPE: "patch"

jobs:
  build-android:
    runs-on: ubuntu-latest
    outputs:
      whitelabel: ${{ steps.vars.outputs.WHITELABEL }}
      bump_type: ${{ steps.vars.outputs.BUMP_TYPE }}

    if: ${{ github.event_name != 'issue_comment' || (github.event.issue.pull_request && startsWith(github.event.comment.body, '/deploy-')) }}
    steps:
      - name: Set vars
        if: github.event_name == 'issue_comment'
        id: vars
        run: |-
          whitelabel=$(echo '${{ github.event.comment.body }}' | sed -n 's|^/deploy-\(.*\)|\1|p')
          bump_type=$(echo '${{ github.event.comment.body }}' | sed -n 's|.*bump_type:\([a-zA-Z0-9_-]*\).*|\1|p')
          echo "WHITELABEL=$whitelabel" >> $GITHUB_ENV
          echo "BUMP_TYPE=$bump_type" >> $GITHUB_ENV
          echo "WHITELABEL=$whitelabel" >> $GITHUB_OUTPUT
          echo "BUMP_TYPE=$bump_type" >> $GITHUB_OUTPUT

      - run: echo "cd mobile/android && bundle exec fastlane deploy flavor:${{ env.WHITELABEL }} bump_type:${{ env.BUMP_TYPE }}"

      - name: Update comment with deployment in progress
        if: github.event_name == 'issue_comment'
        uses: jungwinter/comment@v1
        with:
          type: edit
          body: "${{ github.event.comment.body }}\n\n⏳ [**Build in PROGRESS for ${{ env.WHITELABEL }} whitelabel...**](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          comment_id: ${{ github.event.comment.id }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: "get-branch"
        if: github.event_name == 'issue_comment'
        run: echo "branch=$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')" >> $GITHUB_OUTPUT
        env:
          REPO: ${{ github.repository }}
          PR_NO: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-branch.outputs.branch }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"

      - name: Install Fastlane dependencies
        run: cd mobile/android && bundle install

      - run: "cd mobile/android && bundle exec fastlane build flavor:${{ env.WHITELABEL }} bump_type:${{ env.BUMP_TYPE }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            mobile/android/app/build.gradle

  comment:
    needs: [build-android]
    runs-on: ubuntu-latest

    steps:
      - name: Update comment with deployment success
        if: github.event_name == 'issue_comment' && success()
        uses: jungwinter/comment@v1
        with:
          type: edit
          comment_id: ${{ github.event.comment.id }}
          body: "${{ github.event.comment.body }}\n\n🚀 [**Build SUCCESSFUL for ${{ needs.build-android.outputs.whitelabel }} whitelabel**](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update comment with deployment failure
        if: github.event_name == 'issue_comment' && failure()
        uses: jungwinter/comment@v1
        with:
          type: edit
          comment_id: ${{ github.event.comment.id }}
          body: "${{ github.event.comment.body }}\n\n❌ [**Build FAILED for ${{ needs.build-android.outputs.whitelabel }} whitelabel**](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          token: ${{ secrets.GITHUB_TOKEN }}
