name: Android Build

on:
  issue_comment:
    types: [created, edited, deleted]
  push:
    branches:
      - feat/testing-trigger
  workflow_dispatch:

permissions:
  contents: "write"
  issues: "write"
  pull-requests: write
  id-token: "write"

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'issue_comment' || (github.event.issue.pull_request && startsWith(github.event.comment.body, '/deploy-internal')) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: echo "running"
