name: build

on:
  issue_comment:
    types: [created, edited]
  workflow_dispatch:

permissions:
  contents: "write"
  issues: "write"
  pull-requests: write
  id-token: "write"

env:
  WHITELABEL: ""

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/deploy-internal-') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: echo "WHITELABEL=$(echo '${{ github.event.comment.body }}' | sed -n 's|^/deploy-internal-\(.*\)|\1|p')" >> $GITHUB_ENV

      - name: Set run name
        uses: actions/github-script@v6
        with:
          script: |
            const runName = `${{ github.actor }} is deploying ${{ env.WHITELABEL }} app`;
            github.rest.actions.updateWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.run_id,
              name: runName
            });

      - run: echo "running deployment for $WHITELABEL"
