name: build-android
run-name: ${{ github.actor }} is deploying android app

on:
  issue_comment:
    types: [created, edited, deleted]
  workflow_dispatch:

permissions:
  contents: "write"
  issues: "write"
  pull-requests: "write"
  id-token: "write"

env:
  DEFAULT_WHITELABEL: "tupinamba"
  DEFAULT_BUMP_TYPE: "patch"
  ENV_FILE_TUPI: "tmp/build-production/.env.tupi.prod"
  ENV_FILE_BYD: "tmp/build-production/.env.byd.prod"
  ENV_FILE_MOB: "tmp/build-production/.env.mob.prod"
  ENV_FILE_SHELL: "tmp/build-production/.env.shell.prod"

jobs:
  build-android:
    runs-on: ubuntu-latest
    outputs:
      whitelabel: ${{ steps.build.outputs.WHITELABEL }}

    if: ${{ github.event_name != 'issue_comment' || (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/build-')) }}
    steps:
      - id: "get-branch"
        if: github.event_name == 'issue_comment'
        run: echo "branch=$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')" >> $GITHUB_OUTPUT
        env:
          REPO: ${{ github.repository }}
          PR_NO: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-branch.outputs.branch }}

      - name: Install Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"

      - name: Install Fastlane dependencies
        run: cd mobile/android && bundle install

      - id: "build"
        name: "Build app(s)"
        if: github.event_name != 'issue_comment' || (github.event.issue.pull_request && startsWith(github.event.comment.body, '/build-'))
        run: |
          cd mobile/android

          if [ "${{ github.event_name }}" == "issue_comment" ]; then
            whitelabel=$(echo '${{ github.event.comment.body }}' | sed -n 's|^/build-\([^ ]*\).*|\1|p')
            bump_type=$(echo '${{ github.event.comment.body }}' | sed -n 's|.*bump_type:\([a-zA-Z0-9_-]*\).*|\1|p')

            [[ -z "$whitelabel" ]] && whitelabel="${{ env.DEFAULT_WHITELABEL }}"
            [[ -z "$bump_type" ]] && bump_type="${{ env.DEFAULT_BUMP_TYPE }}"

            echo "WHITELABEL=$whitelabel" >> $GITHUB_OUTPUT

            if [ "$whitelabel" == "all" ]; then
                whitelabels=('tupinamba' 'byd' 'mobilize' 'shellrecharge')
                whitelabels_alias=('tupi' 'byd' 'mob' 'shell')

                for i in "${!whitelabels[@]}"; do
                    wl=${whitelabels[$i]}
                    alias=${whitelabels_alias[$i]}
                    env_file_name="ENV_FILE_${alias^^}"
                    env_file_path=${!env_file_name}
                    bundle exec ENVFILE=$env_file_path fastlane build flavor:$wl bump_type=$bump_type
                done
            else
                env_file_name="ENV_FILE_${whitelabel^^}"
                env_file_path=${!env_file_name}
                gcloud secrets versions access latest --verbosity=debug --project=tupinamba-prod --secret=${whitelabel}-mobile-dot-env --out-file=$env_file_path
                bundle exec fastlane build flavor:$whitelabel bump_type=$bump_type
            fi
          else
            echo "gcloud secrets versions access latest --verbosity=debug --project=tupinamba-prod --secret=${{ env.DEFAULT_WHITELABEL }}-mobile-dot-env --out-file=${ENV_FILE_TUPI}"
            bundle exec ENVFILE=${{ env.ENV_FILE_TUPI }} fastlane build bump_type=${{ env.DEFAULT_BUMP_TYPE }}
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: mobile/android/app/build.gradle

  comment:
    needs: [build-android]
    runs-on: ubuntu-latest

    steps:
      - name: Update comment with deployment success
        if: github.event_name == 'issue_comment' && success()
        uses: jungwinter/comment@v1
        with:
          type: edit
          comment_id: ${{ github.event.comment.id }}
          body: "${{ github.event.comment.body }}\n\n🚀 [**Build SUCCESSFUL for ${{ needs.build-android.outputs.whitelabel }} whitelabel**](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update comment with deployment failure
        if: github.event_name == 'issue_comment' && failure()
        uses: jungwinter/comment@v1
        with:
          type: edit
          comment_id: ${{ github.event.comment.id }}
          body: "${{ github.event.comment.body }}\n\n❌ [**Build FAILED for ${{ needs.build-android.outputs.whitelabel }} whitelabel**](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          token: ${{ secrets.GITHUB_TOKEN }}
